# Site settings
name: 哎呦，又忘了 ✘✘✘的博客
email: 939800704@qq.com
author: W/J
url: http://wenjies.github.io
resume_site: wenjies.github.io/me/
github: https://github.com/wenjies
baseurl: ""  #根目录
description: 假如生活欺骗了你，不要悲伤，不要哭泣。
motto: 我们笑着说再见，却深知再见遥遥无期。
#motto: 如果生活欺骗了你，不要悲伤，不要哭泣。
banner: 愿你走出半生， 归来仍是少年。
#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
excerpt_separator:  '<!-- more -->' #文章摘要
paginate: 8
paginate_path: "page:num"
gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
github_username: wenjie
highlighter: rouge
markdown: kramdown
FB:
  comments :
    provider : disqus
    disqus :
        short_name : wj
